[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "github-email-finder"
version = "1.0.0"
description = "A tool to identify user email addresses from GitHub commit logs"
readme = "README.md"
requires-python = ">=3.8"
authors = [
    { name = "f2nDev" }
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "PyGithub==2.10.0",
]

[project.scripts]
github-email-finder = "github_email_finder:main"
